### ISSUE TITLE
DatePicker not opening, throws error

### ISSUE THREAD

**Issue by LuxsSoft** [mdbootstrap/TW-Elements#1479]
**Describe the bug**
A tried to use the DatePicker element and copied the examples here https://tailwind-elements.com/docs/standard/forms/datepicker/ in a blank nuxt3 component. They all display as expected but the date picker does not actually open the modal to select a date. The following error is thrown in the js:

```
input.js:357 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at d._applyNotch (input.js:357:23)
    at d._getElements (input.js:409:14)
    at input.js:371:12
    at J (index.js:274:5)
    at d._activate (input.js:370:5)
    at HTMLInputElement.<anonymous> (input.js:431:16)
    at HTMLDocument.i (event-handler.js:127:21)
input.js:420 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
    at d._deactivate (input.js:420:18)
    at HTMLInputElement.<anonymous> (input.js:437:16)
    at HTMLDocument.i (event-handler.js:127:21)
input.js:379 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at input.js:379:22
    at J (index.js:274:5)
    at d._activate (input.js:370:5)
    at HTMLInputElement.<anonymous> (input.js:431:16)
    at HTMLDocument.i (event-handler.js:127:21)
(anonymous) @ input.js:379
J @ index.js:274
_activate @ input.js:370
(anonymous) @ input.js:431
i @ event-handler.js:127
input.js:420 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
    at d._deactivate (input.js:420:18)
    at HTMLInputElement.<anonymous> (input.js:437:16)
    at HTMLDocument.i (event-handler.js:127:21)
_deactivate @ input.js:420
(anonymous) @ input.js:437
i @ event-handler.js:127
```

**To Reproduce**
1. Setup a blank nuxt3 project with nuxt 3.2.0 and add tailwind elements through the cdn as described here https://tailwind-elements.com/docs/standard/getting-started/quick-start/
2. Create a blank new component and copy any of the datepicker options into the template section  https://tailwind-elements.com/docs/standard/forms/datepicker/ 
3. Should now see the input field
4.  Click the input field and have a look at the console. Nothing happens but the error is thrown

**Expected behavior**
Expect the date modal popup to show

**Actual behavior**
Nothing happen on click, error is thrown

**Show your code**
```
<template>
  <div class="flex items-center justify-center">
    <div
      class="relative mb-3 xl:w-96"
      data-te-datepicker-init
      data-te-input-wrapper-init>
      <input
        type="text"
        class="peer block min-h-[auto] w-full rounded border-0 bg-transparent py-[0.32rem] px-3 leading-[2.15] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0"
        placeholder="Select a date"
        data-te-datepicker-toggle-ref
        data-te-datepicker-toggle-button-ref />
      <label
        for="floatingInput"
        class="pointer-events-none absolute top-0 left-3 mb-0 max-w-[90%] origin-[0_0] truncate pt-[0.37rem] leading-[2.15] text-neutral-500 transition-all duration-200 ease-out peer-focus:-translate-y-[1.15rem] peer-focus:scale-[0.8] peer-focus:text-primary peer-data-[te-input-state-active]:-translate-y-[1.15rem] peer-data-[te-input-state-active]:scale-[0.8] motion-reduce:transition-none dark:text-neutral-200 dark:peer-focus:text-neutral-200"
        >Select a date</label
      >
    </div>
  </div>
</template>

<script setup>
const iframe = ref(null)


</script>
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 
 - Browser Chrome

**Comment by Trochonovitz** [comment]
Hi, try import TE via CDN this way - in `nuxt.config.js`. FYI in following days we are going to release integration tutorials with most popular CSR and SSR frameworks so stay tuned.
```
app: {
  head: {
    script: [
      {
        src: "https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js",
      },
    ],
  },
},
```

**Comment by LuxsSoft** [comment]
Thx for the response. @Trochonovitz i have imported it as you suggested. It still throws the same error

**Comment by Trochonovitz** [comment]
We prepared a fix for pickers to working with frameworks, currently waiting for beta2 release. About this error: we are looking into this. For now you got to import library like this:
```
onMounted(() => {
  const importTE = async () => {
    await import("tw-elements");
  };
  importTE();
});
```
