### ISSUE TITLE
Components not working properly when updated to 1.0.0-beta3 from 1.0.0-beta2

### ISSUE THREAD

**Issue by rajesh-kanhasoft** [mdbootstrap/TW-Elements#1859]
I am using tw-elmenent of datepicker and getting following error, not only for the datepicker for all components getting same issues

ERROR
Cannot read properties of null (reading 'setAttribute')
TypeError: Cannot read properties of null (reading 'setAttribute')
    at http://localhost:3002/static/js/bundle.js:230549:36
    at il (http://localhost:3002/static/js/bundle.js:226333:23)
    at W._activate (http://localhost:3002/static/js/bundle.js:230545:5)
    at HTMLInputElement.<anonymous> (http://localhost:3002/static/js/bundle.js:230565:9)
    at HTMLDocument.i (http://localhost:3002/static/js/bundle.js:226392:159)

**Comment by juujisai** [comment]
Hi, I cannot recreate your issue. I've created a new vite app, used picker and it's working as it should. What stack are you using? How are you adding the `tw-elements` package to your project? Can you provide some code where you experience your issues? Can you create a new app with fresh installation and check if the issue still occurs?

https://tailwind-elements.com/docs/standard/getting-started/quick-start/
