### ISSUE TITLE
[Autocomplete] [bug in element]

### ISSUE THREAD

**Issue by asasem** [mdbootstrap/TW-Elements#2293]
in Autocomplete Async component
when I click on the No results found field

then an error appears in the console

manipulator.js:108 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at Object.getDataAttribute (manipulator.js:108:7)
    at _id._handleItemsClick (index.js:643:9)
    at HTMLUListElement.e (event-handler.js:137:1)

is it possible to fix it?

In the example on the site the error is also  @present
![2024-01-25_13-21-01](https://github.com/mdbootstrap/TW-Elements/assets/7801474/2ff6cffa-5efa-432b-8105-706ad3f3583c)

![2024-01-25_13-34-17](https://github.com/mdbootstrap/TW-Elements/assets/7801474/4e6908fe-2895-4df1-a3bb-4552bf914c7d)

**Comment by iprzybysz** [comment]
Hi @asasem, thanks for reporting this bug. I've added it to our repository. We'll fix it as soon as possible.
